// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	models "github.com/AlejandroAldana99/yalo-challenge/models"
	mock "github.com/stretchr/testify/mock"
)

// IHealthService is an autogenerated mock type for the IHealthService type
type IHealthService struct {
	mock.Mock
}

// CheckPod provides a mock function with given fields: chanHealth
func (_m *IHealthService) CheckPod(chanHealth chan models.HealthComponentDetail) {
	_m.Called(chanHealth)
}

// NewIHealthService creates a new instance of IHealthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIHealthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IHealthService {
	mock := &IHealthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
