// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	models "github.com/AlejandroAldana99/yalo-challenge/models"
	mock "github.com/stretchr/testify/mock"
)

// IInteractionsService is an autogenerated mock type for the IInteractionsService type
type IInteractionsService struct {
	mock.Mock
}

// CollectUserInteractions provides a mock function with given fields: interactions
func (_m *IInteractionsService) CollectUserInteractions(interactions []models.UserInteraction) error {
	ret := _m.Called(interactions)

	if len(ret) == 0 {
		panic("no return value specified for CollectUserInteractions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]models.UserInteraction) error); ok {
		r0 = rf(interactions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIInteractionsService creates a new instance of IInteractionsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIInteractionsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IInteractionsService {
	mock := &IInteractionsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
