// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	models "github.com/AlejandroAldana99/yalo-challenge/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// IStoreRepository is an autogenerated mock type for the IStoreRepository type
type IStoreRepository struct {
	mock.Mock
}

// AddInteraction provides a mock function with given fields: userID, interactions
func (_m *IStoreRepository) AddInteraction(userID string, interactions []models.UserInteraction) error {
	ret := _m.Called(userID, interactions)

	if len(ret) == 0 {
		panic("no return value specified for AddInteraction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []models.UserInteraction) error); ok {
		r0 = rf(userID, interactions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetInteractions provides a mock function with given fields: userID, since
func (_m *IStoreRepository) GetInteractions(userID string, since time.Time) ([]models.UserInteraction, error) {
	ret := _m.Called(userID, since)

	if len(ret) == 0 {
		panic("no return value specified for GetInteractions")
	}

	var r0 []models.UserInteraction
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time) ([]models.UserInteraction, error)); ok {
		return rf(userID, since)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time) []models.UserInteraction); ok {
		r0 = rf(userID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserInteraction)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time) error); ok {
		r1 = rf(userID, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIStoreRepository creates a new instance of IStoreRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIStoreRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IStoreRepository {
	mock := &IStoreRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
